package Exceptiontrycatch;

public class throwandthrows {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
finalclass.getclass();
	}

}

class finalclass {
	public static void getclass() {
		throw new ArithmeticException("It's value is zero");
	}
}